### ISSUE TITLE
Creating new Ontology via REST API throwing 500 Internal Server Error

### ISSUE THREAD

**Issue by tmirza95** [ncbo/ontologies_api#110]
I tried to create new ontology via REST API, endpoint: 

- https://data.bioontology.org/ontologies/
- TYPE: POST

It returns 500 internal server error. For creating new ontology via REST, no example is available. Help needed in both of these queries.

Sample payload:

`{
"hasOntologyLanguage": "OWL",
"contact": [
    {
        "id": "https://data.bioontology.org/contacts/098b1fa0-773c-0136-f4a6-005056010074",
        "name": "NCICB Support",
        "email": "ncicbiit@mail.nih.gov"
    }
],
"released": "2023-01-01T18:12:22-08:00",
"acryonym": "XYZZ",
"name": "ResearchXYZ Ontology"
}`

Not enough examples are available to POST a new ontology via REST. What is missing here?

**Comment by jvendetti** [comment]
Hello @tmirza95. We don't use GitHub issues for questions. Instead, please post this on the [BioPortal support list](https://mailman.stanford.edu/mailman/listinfo/bioontology-support).
