### ISSUE TITLE
Unable to download ATC ontologies

### ISSUE THREAD

**Issue by viraxslot** [ncbo/ontologies_api#123]
Hello,

I'm trying to download ATC ontologies with the following request:
`curl --location 'http://data.bioontology.org/ontologies/ATC/download?apikey=<API_KEY>&download_format=csv'`

The result is:
<img width="724" alt="image" src="https://github.com/ncbo/ontologies_api/assets/20737672/cb9b446f-2ab6-4725-b0f4-12eed2bddced">

As I can see the last submission for ATC is 20:
`curl --location 'http://data.bioontology.org/ontologies/ATC/latest_submission/?apikey=<API_KEY>`

<img width="645" alt="image" src="https://github.com/ncbo/ontologies_api/assets/20737672/95a0f5d7-dde2-42e9-a7ba-22db73d26f9a">

**Could you please fix the issue?**

I tried to download other ontologies and there is no problem there (BRO as an example):
<img width="1069" alt="image" src="https://github.com/ncbo/ontologies_api/assets/20737672/c4c09617-6c76-4748-b9c9-ce4022d96fb0">

**Comment by alexskr** [comment]
we are working on UMLS2023AA release at the moment and expect to complete it in the next couple of days.

**Comment by viraxslot** [comment]
@alexskr thank you for the quick response.
Is there any possibility to get the old version of this file? Because currently we're blocked due to this error.
