### ISSUE TITLE
Feature Request: Add API call to trigger ontology pull from remote location

### ISSUE THREAD

**Issue by alexskr** [ncbo/ontologies_api#127]
BioPortal has a mechanism for downloading ontology files from remote URLs and triggering a new submission when change is detected.  This process runs on a daily schedule which currently set to once-a-day.  The delay can causes a significant friction for users who need the new version of ontology/vocabulary to show up quicker in BioPortal. 

ncbo_cron has a script that can be run from the command line to kick off ontology pull so we would need to add ability to trigger ontology pull from the api side so that it can be used in the ontology development pipelines. 

For example, ontology development hosted in github could add a GitHub webhook or GitHub action to trigger BioPortal/OntoPortal pull mechanism when a new version of ontology is published.

**Comment by jonquet** [comment]
This can be planned as one of the utils for the 'admin' tab for a given ontology that we plan to do with @syphax-bouazzouni

**Comment by alexskr** [comment]
> This can be planned as one of the utils for the 'admin' tab for a given ontology that we plan to do with @syphax-bouazzouni

yes, if we have that functionality in the API then we can enable ontology owners to trigger pull it from the UI.

**Comment by alexskr** [comment]
Sample GitHub action script for triggering pull of an ontology https://github.com/ncbo/ncbo_rest_sample_code/blob/master/github_actions/publish_to_bioportal.yml

**Comment by jonquet** [comment]
> > This can be planned as one of the utils for the 'admin' tab for a given ontology that we plan to do with @syphax-bouazzouni
> 
> 
> yes, if we have that functionality in the API then we can enable ontology owners to trigger pull from the UI.

Thanks I better understand the goal of the GitHub Action now. Might be useful indeed, especially when GitHub users have a process to produce their file directly on GitHub.

**Comment by jonquet** [comment]
I would recommend to create the issue in the UI repo to think/discuss/design the corresponding UI for triggering this. A simple button or additional action in the Ontology Administration tab might be sufficient. 
But if we don't do a UI folks will never know the back service.
