### ISSUE TITLE
Searching term in MESH ontology returns different ontology source(STY) in response

### ISSUE THREAD

**Issue by reinertisa** [ncbo/ontologies_api#157]
Hi, when I try to get MESH ontology for behavior, I get MESH and STY in response. Why do I get STY in response? I explicitly set `ontologies=MESH` and `require_exact_match=true`
**End point**: https://data.bioontology.org/search?q=behavior&ontologies=MESH&require_exact_match=true

When I try to the same end point using ontologies=STY, I just see STY in response. This is what I expect. 
**End point:** https://data.bioontology.org/search?q=behavior&ontologies=STY&require_exact_match=true 

Thank you for your help in advance. If you need anything from me, please let me know.

**Comment by jvendetti** [comment]
Hi @reinertisa

The MESH vocabulary we serve in BioPortal is from the National Library of Medicine's [UMLS Metathesaurus](https://www.nlm.nih.gov/research/umls/knowledge_sources/metathesaurus/index.html). UMLS vocabularies aren't distributed in any format that BioPortal supports, so we had to develop a program that transforms MESH and other UMLS vocabularies from a UMLS database instance to RDF. The program is open source and available here: https://github.com/ncbo/umls2rdf.

As part of the transformation, we include UMLS semantic type information in each of the vocabulary files. The main purpose for doing so is to allow BioPortal's [Annotator](https://bioportal.bioontology.org/annotator) to filter annotations based on semantic types. This topic has been discussed in more detail on our support list: https://mailman.stanford.edu/pipermail/bioontology-support/2018-July/010459.html.

The result set you're getting from the first endpoint you listed above (https://data.bioontology.org/search?q=behavior&ontologies=MESH&require_exact_match=true), isn't returning results from MESH and STY. It's only returning results from MESH, which includes a modeling of UMLS semantic types in the vocabulary source file. If you download MESH.ttl from our site, you can see in the file contents where both of these classes are declared:

Line 4,659,926 of MESH.ttl:

```TTL
<http://purl.bioontology.org/ontology/MESH/D001519> a owl:Class ;
  skos:prefLabel """Behavior"""@en ;
  skos:notation """D001519"""^^xsd:string ;
```

Line 10,686,092 of MESH.ttl:

```TTL
<http://purl.bioontology.org/ontology/STY/T053> a owl:Class ;
  skos:notation "T053"^^xsd:string ;
  skos:prefLabel "Behavior"@en .
```

I hope this information is helpful.

**Comment by reinertisa** [comment]
@jvendetti Thank you for your comment. It is helpful. Have a nice day.
