### ISSUE TITLE
Endpoint for retrieving ontology property tree (CEDAR)

### ISSUE THREAD

**Issue by mdorf** [ncbo/ontologies_api#27]
Similar to the class tree endpoint, we need a service that retrieves a property tree for a given property, identified by its ID.

**Comment by jonquet** [comment]
This could be also related to https://github.com/agroportal/agroportal_web_ui/issues/55
As adding features for property in BioPortal would be nice.
(perso: I would even also add property label to the Annotator dictionary with a specific option to activate those matching)

**Comment by mdorf** [comment]
/ontologies/:ontology/properties/:propery/tree

**Comment by mdorf** [comment]
This endpoint will return ALL roots, with the node expanded, corresponding to the path to the given property. This behavior is identical to the class tree endpoint.
