### ISSUE TITLE
Inconsistency in returning private ontologies

### ISSUE THREAD

**Issue by jonquet** [ncbo/ontologies_api#45]
Take for example the ontology ICD10CDC which is private on BioPortal.

/ontologies call does not return it: 
http://data.bioontology.org/ontologies?display_links=false&display_context=false

Whereas 
/submissions call does return it: 
http://data.bioontology.org/submissions?&display_links=false&display_context=false

This could be a design choice to return private ontologies as this is only the metadata, but it seems that the design choice should be consistent btw the 2 calls.

**Comment by alexskr** [comment]
addressed by https://github.com/ncbo/ontologies_api/pull/126
