### ISSUE TITLE
Mappings service pagination returns empty results

### ISSUE THREAD

**Issue by mdorf** [ncbo/ontologies_api#48]
http://data.bioontology.org/mappings?ontologies=NCIT,DOID&page=66

For NCIT and DOID, there are 180 pages reported
"page": 66,
"pageCount": 180,
"totalCount": 8986

However, anything beyond page 66 returns empty results.

**Comment by graybeal** [comment]
This appears to be working, likely due to work on #115.

**Comment by mdorf** [comment]
fixed, deployed
