### ISSUE TITLE
Irregularites in results between /mappings and /classes/:cls/mappings endpoints

### ISSUE THREAD

**Issue by jvendetti** [ncbo/ontologies_api#50]
Initially [reported by an end user](http://ncbo-support.2288202.n4.nabble.com/bioontology-support-Ontology-mapping-tp4656476p4656579.html) on the support list.

The REST call to get all mappings between IOBC and MESH returns an empty collection:

http://data.bioontology.org/mappings?ontologies=IOBC,MESH

![screenshot 2018-07-23 15 04 14](https://user-images.githubusercontent.com/1696923/43105424-af7e0412-8e89-11e8-8c97-1993e5274cbd.png)

However, if you issue a REST call to get all mappings for a particular class in IOBC, the result set contains a mapping between said class and a class in MESH:

http://data.bioontology.org/ontologies/IOBC/classes/http%3A%2F%2Fpurl.jp%2Fbio%2F4%2Fid%2F200906053522984593/mappings

![screenshot 2018-07-23 15 08 25](https://user-images.githubusercontent.com/1696923/43105600-52d126a8-8e8a-11e8-8b84-580ca2b1648b.png)

Something else of note about this class - [clicking on the PURL](http://purl.jp/bio/4/id/200906053522984593) will open the classes page in BioPortal with the class details correctly displayed on the right-hand side of the UI, but the left-hand side has no occurrences of the class in the class tree.

![screenshot 2018-07-23 15 25 37](https://user-images.githubusercontent.com/1696923/43106255-c1c7ed38-8e8c-11e8-881c-8c8c1bd5f93d.png)

**Comment by jvendetti** [comment]
We just got [another report](http://ncbo-support.2288202.n4.nabble.com/bioontology-support-BioPortal-Feedback-from-chen-yang-ugent-be-tp4656618p4656626.html) on the support list of this behavior.

If you issue a REST call to get all the mappings between ONE and NCIT, you get an empty result set:

http://data.bioontology.org/mappings?ontologies=ONE,NCIT

![screenshot 2018-08-13 11 19 47](https://user-images.githubusercontent.com/1696923/44050105-ceed8e32-9eea-11e8-979f-79642eecc3be.png)

However, if you issue a REST call to get the mappings for the "Administration" class in the ONE ontology, you get a result set that includes a class from NCIT:

http://data.bioontology.org/ontologies/ONE/classes/http%3A%2F%2Fncicb.nci.nih.gov%2Fxml%2Fowl%2FEVS%2FThesaurus.owl%23C25409/mappings

![screenshot 2018-08-13 11 23 10](https://user-images.githubusercontent.com/1696923/44050320-7c736270-9eeb-11e8-9a7e-225d670b8382.png)

**Comment by jvendetti** [comment]
Received [another report](http://ncbo-support.2288202.n4.nabble.com/bioontology-support-BioPortal-Feedback-from-Philip-van-Damme-tp4657710p4657759.html) on the support list about this behavior.

If you issue a REST call to [get the mappings](https://data.bioontology.org/ontologies/ORDO/classes/http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_3389/mappings?display_context=false&display_links=false) for the "Tuberculosis" class in the ORDO ontology, the result set includes a mapping to the "Tuberculosis" class in SNOMED CT:

![Screenshot 2020-04-28 10 46 10](https://user-images.githubusercontent.com/1696923/80524065-e241d200-8943-11ea-8850-3c9553ae91ba.png)

However, if you issue a REST call to [get all the mappings](http://data.bioontology.org/mappings?ontologies=ORDO,SNOMEDCT&display_context=false&display_links=false) between ORDO and SNOMED CT, the result set doesn't include the LOOM mapping for the "Tuberculosis" class.

**Comment by graybeal** [comment]
This is fixed, mappings call http://data.bioontology.org/mappings?ontologies=IOBC,MESH now returns 32859 mappings. 

Probably fixed due to recent work on #115 and similar.
