### ISSUE TITLE
extract ontology from EDAM BioPortal using python

### ISSUE THREAD

**Issue by robertjeremy1** [ncbo/ontologies_api#88]
This is my first time using an API in Python. I want to extract ontology using python script . can someone tell me how to do it ? 
there is an existing python script ?

**Comment by jvendetti** [comment]
@robertjeremy1 - we have some Python code examples for working with the BioPortal REST API in this repository:

https://github.com/ncbo/ncbo_rest_sample_code/tree/master/python/python3

You'll need an API key to issues calls to the API. Instructions for getting one are here:

https://www.bioontology.org/wiki/BioPortal_Help#Getting_an_API_key

If you have follow-up questions, please reach out to us via our support list:

https://mailman.stanford.edu/mailman/listinfo/bioontology-support
